## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_Internet-Gateway-vcn-20200722-2035 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "Internet Gateway vcn-20200722-2035"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_vcn-20200722-2035.id
}

resource oci_core_public_ip export_publicip20210301213542 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "publicip20210301213542"
  freeform_tags = {
    "gatewayId" = oci_apigateway_gateway.export_app-gw.id
  }
  lifetime      = "RESERVED"
  private_ip_id = oci_core_private_ip.export_privateip20210301213542.id
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_subnet export_Public-Subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  dhcp_options_id = oci_core_vcn.export_vcn-20200722-2035.default_dhcp_options_id
  display_name    = "Public Subnet"
  dns_label       = "subnet"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcn-20200722-2035.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn-20200722-2035.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn-20200722-2035.id
}

resource oci_core_private_ip export_vnic20210301213543 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "vnic20210301213543"
  freeform_tags = {
    "gatewayId" = oci_apigateway_gateway.export_app-gw.id
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.0.5"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljronpmjedh36spfumk6fjbjn3wm3xrt7frpt7f56mkvssmpo5h5lcq"
}

resource oci_core_private_ip export_privateip20210301213542 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "privateip20210301213542"
  freeform_tags = {
    "gatewayId" = oci_apigateway_gateway.export_app-gw.id
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.0.6"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljronpmjedh36spfumk6fjbjn3wm3xrt7frpt7f56mkvssmpo5h5lcq"
}

resource oci_core_private_ip export_vnic20210301213543_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "vnic20210301213543"
  freeform_tags = {
    "gatewayId" = oci_apigateway_gateway.export_app-gw.id
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.0.7"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljs3j6ailjaiwmbje3rw26s7vkcpzttr5hpsbse43mepnvblj442m6a"
}

resource oci_core_private_ip export_instance-20210301-1953_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "instance-20210301-1953"
  freeform_tags = {
  }
  hostname_label = "instance-20210301-1953"
  ip_address     = "10.0.0.9"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljs3zvtccn4be6cccla5nbgkakn7qnoiqh33jqzsbonmzfpzbxootrq"
}

resource oci_core_vcn export_vcn-20200722-2035 {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "vcn-20200722-2035"
  dns_label    = "vcn"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn-20200722-2035 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "Default DHCP Options for vcn-20200722-2035"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn-20200722-2035.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn-20200722-2035 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "Default Route Table for vcn-20200722-2035"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn-20200722-2035.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-vcn-20200722-2035.id
  }
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn-20200722-2035 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "Default Security List for vcn-20200722-2035"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Everything"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn-20200722-2035.default_security_list_id
}

