## This configuration was generated by terraform-provider-oci

resource oci_identity_compartment export_CBI {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "rshade@flexera.com"
    "Oracle-Tags.CreatedOn" = "02-26-2021"
  }
  description = "CBI Compartment"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "CBI"
}

resource oci_identity_dynamic_group export_CBI_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = "2021-03-01T18:49:14.217Z"
  }
  description = "CBI Dynamic Group"
  freeform_tags = {
  }
  matching_rule = "Any {ALL {resource.type = 'fnfunc', resource.compartment.id = '"+ var.compartment_ocid +"'}}"
  name          = "CBI"
}

resource oci_identity_dynamic_group export_CBI-AppGW {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = "2021-03-01T23:05:06.948Z"
  }
  description = "CBI-AppGW"
  freeform_tags = {
  }
  matching_rule = "Any {ALL {resource.type = 'ApiGateway', resource.compartment.id = '"+ var.compartment_ocid +"'}}"
  name          = "CBI-AppGW"
}

resource oci_identity_policy export_CBIAPPGW {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = "2021-03-01T23:07:31.795Z"
  }
  description = "CBIAPPGW"
  freeform_tags = {
  }
  name = "CBIAPPGW"
  statements = [
    "Allow dynamic-group  CBI-AppGW to use functions-family in compartment id "+ var.compartment_ocid +"",
    "ALLOW any-user to use functions-family in compartment id "+ var.compartment_ocid +" where ALL {request.principal.type= 'ApiGateway', request.resource.compartment.id= '"+ var.compartment_ocid +"'}",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_CBIPolicy {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = "2021-03-01T18:46:43.405Z"
  }
  description = "CBIPolicy"
  freeform_tags = {
  }
  name = "CBIPolicy"
  statements = [
    "define tenancy usage-report as ocid1.tenancy.oc1..aaaaaaaaned4fkpkisbwjlr56u7cj63lf3wffbilvqknstgtvzub7vhqkggq",
    "endorse dynamic-group CBI to read objects in tenancy usage-report",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_user export_oracleidentitycloudservice-rshade-flexerasoftware-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "scim-service"
    "Oracle-Tags.CreatedOn" = "2020-07-23T01:38:30.356Z"
  }
  description = "Richard Shade"
  email       = "rshade@flexera.com"
  freeform_tags = {
  }
  name = var.tag_created_by
}

resource oci_identity_user export_rshade-flexerasoftware-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
  }
  description = "Richard Shade"
  email       = "rshade@flexerasoftware.com"
  freeform_tags = {
  }
  name = "rshade@flexerasoftware.com"
}

resource oci_identity_api_key export_oracleidentitycloudservice-rshade-flexerasoftware-com_api_key_1 {
  key_value = "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApdaTtMJPYHDZGN1OegSl\r\nohrUD3XGTuq419/rVYVOGGT1y4li4Pwl+Z+cxWrIbcmzlnocZxt8KMb8WFftIK5U\r\nQBw+269n23v3sTo3X/Y9EE056n90EJ4UVjy3tgvaS2BHsQcA5gb6urYN7ykNTIl9\r\nRmRuts8iCaxR2MrgULpc4JRLtxd4zH5kULr9JJihbw0b13M1DC3EsbFZ1Jmy7/3G\r\nSK0cAQTxpE917Vgp4tkxkhU+YgF4u8ZjNZWv2qMaswhsexIFYGTukJdDWTQ2Bfea\r\njRkGlDtc9o6rriXwnijR98A4IxxvtBU2NUkku+8IZYSrrVTWELF1F/CVEofhzcxq\r\nEQIDAQAB\r\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_oracleidentitycloudservice-rshade-flexerasoftware-com.id
}

resource oci_identity_auth_token export_oracleidentitycloudservice-rshade-flexerasoftware-com_auth_token_1 {
  description = "registry"
  user_id     = oci_identity_user.export_oracleidentitycloudservice-rshade-flexerasoftware-com.id
}

resource oci_identity_swift_password export_oracleidentitycloudservice-rshade-flexerasoftware-com_swift_password_1 {
  description = "registry"
  user_id     = oci_identity_user.export_oracleidentitycloudservice-rshade-flexerasoftware-com.id
}

resource oci_identity_ui_password export_oracleidentitycloudservice-rshade-flexerasoftware-com_ui_password {
  user_id = oci_identity_user.export_oracleidentitycloudservice-rshade-flexerasoftware-com.id
}

resource oci_identity_ui_password export_rshade-flexerasoftware-com_ui_password {
  user_id = oci_identity_user.export_rshade-flexerasoftware-com.id
}

resource oci_identity_user_group_membership export_rshade-flexerasoftware-com_user_group_membership_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_rshade-flexerasoftware-com.id
}

