## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_Default_Group {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = "2021-03-01T18:54:48.624Z"
  }
  description  = "The log group auto created for the users in selected comparmtent"
  display_name = "Default_Group"
  freeform_tags = {
  }
}

resource oci_logging_log export_Web_Server_execution {
  configuration {
    compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
    source {
      category    = "execution"
      resource    = oci_apigateway_deployment.export_Web-Server.id
      service     = "apigateway"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "Web_Server_execution"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_Web_Server_access {
  configuration {
    compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
    source {
      category    = "access"
      resource    = oci_apigateway_deployment.export_Web-Server.id
      service     = "apigateway"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "Web_Server_access"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_oracle_bill_upload_invoke {
  configuration {
    compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
    source {
      category    = "invoke"
      resource    = oci_functions_application.export_oracle_bill_upload.id
      service     = "functions"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = var.tag_created_by
    "Oracle-Tags.CreatedOn" = var.tag_created_on
  }
  display_name = "oracle_bill_upload_invoke"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

